name: CI Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [ 18.x ]  

    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      # Make a Docker image & Push to docker container.
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: docker build -t samthemaverick/my-portfolio .
      - name: Push Docker Image
        run: docker push samthemaverick/my-portfolio:latest